// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdbjhosvdycplbqhcdhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkYmpob3N2ZHljcGxicWhjZGhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNTM1MDUsImV4cCI6MjA1NjgyOTUwNX0.K93FinQTrlqfNa0JJmZ5AS0T8YZ9GB2GobUsqcb4CWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);